#ifndef NAMEBREAK_CUDA_CONSTANTS_H
#define NAMEBREAK_CUDA_CONSTANTS_H

#define ALPHABET_SIZE 49
#define MAX_CANDIDATE_LEN 16
#define MAX_FILENAME_LEN 128
#define MAX_MATCHES 1024

#endif //NAMEBREAK_CUDA_CONSTANTS_H
