# fly.toml app configuration file generated for namebreak-coordinator on 2026-09-05T16:23:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'namebreak-coordinator'
primary_region = 'arn'

[build]
  dockerfile = 'server/Dockerfile'

[env]
  BIND_ADDR = '0.0.0.0:8080'
  DATABASE_URL = 'sqlite:///data/namebreak.db'

[[mounts]]
  source = 'namebreak_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
